%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% MRiLab auto generated file: DO NOT EDIT!     %
% Generated by MRiLab "DoWriteXML2m" Generator %
% MRiLab Version v1.0a                         %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [t, ind, Disp, Axis, Ang]=Mot_RotateHead
%====================================
p.Angle='sin(0.1*t)';
p.Axis=[0;0;1];
p.dt=1;
p.tEnd=100;
p.tStart=0;
[tt, Dispt, Axist, Angt]=MotRotate(p);
t=tt;
ind=ones(1,length(tt));
Disp=Dispt;
Axis=Axist;
Ang=Angt;
p=[];
%--------------------
end
